# Copyright 2016 The Monyhar Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("images") {
  sources = [
    "monyhar_branded_image_provider.h",
    "monyhar_branded_image_provider.mm",
  ]
  deps = [
    "resources:monyhar_ios_made",
    "resources:monyhar_ipados_made",
    "resources:monyhar_non_default_promo",
    "resources:monyhar_stay_safe",
    "resources:download_drivium",
    "//base",
    "//ios/chrome/app/theme",
    "//ios/public/provider/chrome/browser",
    "//ios/public/provider/chrome/browser/images",
    "//ui/base",
  ]
  configs += [ "//build/config/compiler:enable_arc" ]
}
